### ISSUE TITLE
Create pubspec.yaml

### ISSUE THREAD

**Issue by martinrybak** [VGVentures/nitpicky#2]
Required to be used with pub

**Comment by mockturtl** [comment]
@martinrybak look OK?

**Comment by martinrybak** [comment]
I think the description could be less grandiose lol just `Dart static analysis rules used by Very Good Ventures` or similar

**Comment by mockturtl** [comment]
Haha, yeah that came from pedantic.  I guess it matters now that this is public :rofl:

**Comment by mockturtl** [comment]
@martinrybak Come to think of it, does GitHub have any allowance for a public repo, but private issues?  I'll have to keep in mind the discussion here is world-facing...
